name: WeavingSim
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: jadedResearcher

environment:
  sdk: '>=2.8.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.6.0

dependencies:
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
  ImageLib:
    git:
      url: git://github.com/FarragoFiction/ImageLib.git